#!/usr/bin/env bash
set -e
#set -x

SCRIPTPATH=""
SCRIPTARGS=""
CONDAENV=""
CWD=""

CMD=""

while [[ $# -gt 0 ]]; do
    key="$1"
    case ${key} in
    -s|--script)
        SCRIPTPATH="$2"
        shift 2
        ;;
    -a|--args)
        SCRIPTARGS="$2"
        shift 2
        ;;
    -c|--conda)
        CONDAENV="$2"
        shift 2
        ;;
    -w|--cwd)
        CWD="$2"
        shift 2
        ;;
    --)
        shift
        break
        ;;
    *)
        echo "Ignoring unknown wrapper argument: \"$1\""
        shift
        ;;
    esac
done

# For python interpreter to release stdout line by line, and not after job termination
export PYTHONUNBUFFERED=1

if [ "$#" -lt "1" ]; then
    echo "Script path is not specified"
    exit -1
fi
SCRIPTPATH="$1"
shift
SCRIPTARGS="$@"

# validate launchable script is specified
if [ -z "${SCRIPTPATH}" -o ! -f "${SCRIPTPATH}" ]; then
    echo "Valid script must be specified with -s|--script key"
    exit -1
fi

CMD="${SCRIPTPATH}"

if [ ! -z "${SCRIPTARGS}" ]; then
    CMD="${CMD} ${SCRIPTARGS}"
fi

# Lifting affinity constraints
CPU_CORES_ENUM=$(seq -s, 0 $(($(cat /proc/cpuinfo | grep processor | wc -l)-1)))
CMD="taskset -c ${CPU_CORES_ENUM} ${CMD}"

# Sets CUDA devices order to match the one used in nvidia-smi https://github.com/wookayin/gpustat
export CUDA_DEVICE_ORDER=PCI_BUS_ID

# Sets CUDA devices visibility according to SGE allocation policy
export CUDA_VISIBLE_DEVICES="$(ls -rt /tmp/lock-gpu*/info.txt | xargs grep -h  $(whoami) | awk '{print $2}' | paste -sd "," -)"

echo ======= ENV ========
export
echo ======= ENV ========
echo Starting on: `date`

if [ ! -z "${CONDAENV}" ]; then
    echo "Activating conda environment: ${CONDAENV}"
    source activate "${CONDAENV}"
fi

SCRIPTDIR=${SCRIPTPATH%/*}
if [ -d "${SCRIPTDIR}/.git" ]; then
    echo "Repository snapshot info:"
    git --git-dir="${SCRIPTDIR}/.git" remote -v
    git --git-dir="${SCRIPTDIR}/.git" branch -v
fi

echo "Disk and shared memory usage info:"
df -h

echo "About to execute: \"${CMD}\" from \"${CWD}\""
mkdir -p "${CWD}" && cd "${CWD}"
exec ${CMD}

echo Finished at: `date`
